language: node_js
node_js:
  - node
provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: dist
before_install:
  - git config --global user.email "testbot@test.test"
  - git config --global user.name "testbot"
  - git config --global gc.reflogExpire "7 days"
  - git config --global gc.reflogExpireUnreachable "7 days"
  - export FORCE_COLOR=1
before_script:
script:
  - npm run build-production
