language: node_js
node_js:
  - node
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: dist
  verbose: true
  target_branch: gh-pages
before_install:
#  - git config --global user.email "testbot@test.test"
#  - git config --global user.name "testbot"
#  - git config --global gc.reflogExpire "7 days"
#  - git config --global gc.reflogExpireUnreachable "7 days"
  - export FORCE_COLOR=1
  - npm i -g yarn
install:
  - yarn
before_script:
  - git version
script:
  #- yarn run build-production
#  - yarn run fetch-api-json
  - yarn run build
#  - yarn run deploy-ghpages
